language: python
cache: pip
python: "3.6"
notifications:
  email: false
install:
  - pip3 install -r requirements.txt
script:
  - coverage run manage.py unit_test
  - coverage report  # Required coverage threshold specified in .coveragerc
  - find . -name '*.py' -not -path './docs/source/*' -exec pylint '{}' +
  - mypy . --ignore-missing-imports
  - bandit -r .  # Configuration in .bandit
  - sphinx-build -W docs/source docs/build
after_success:
  - coveralls
